name: clickcart_client
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0-171.0.dev

dependencies:
  flutter:
    sdk: flutter
  dropdown_button2: ^2.3.9
  get: ^4.7.2
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  get_storage: ^2.1.1
  json_annotation: ^4.9.0
  otp_text_field_v2: ^1.0.3
  razorpay_flutter: ^1.4.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
flutter:

  uses-material-design: true
